import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { MetaTags } from "@/components/MetaTags";
import { Button } from "@/components/ui/button";
import { Sparkles } from "lucide-react";
import { fetchPetDetails } from "@/services/petService";
import { CareInstructionsSection } from "@/components/CareInstructionsSection";

const FINNEGAN_ID = "297d1397-c876-4075-bf24-41ee1862853a";

export default function DemoCare() {
  const navigate = useNavigate();
  const [pet, setPet] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const petData = await fetchPetDetails(FINNEGAN_ID);
        setPet(petData);
      } catch (error) {
        console.error("Error loading demo pet:", error);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-2 border-primary border-t-transparent" />
      </div>
    );
  }

  if (!pet) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p>Unable to load demo data</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-brand-cream via-white to-brand-cream">
      <MetaTags 
        title={`${pet.name}'s Care & Handling Instructions - Live PetPort Demo`}
        description={`Experience a real PetPort Care & Handling page - ${pet.name}'s complete care instructions, routines, and emergency protocols`}
        image="https://dxghbhujugsfmaecilrq.supabase.co/storage/v1/object/public/og-images/resume-og-1mb.png"
        url={`https://petport.app/demo/care`}
      />

      {/* Live Demo Banner */}
      <div className="bg-gradient-to-r from-brand-primary via-brand-secondary to-brand-primary text-white py-3 px-4 text-center sticky top-0 z-50 shadow-lg">
        <div className="max-w-4xl mx-auto flex items-center justify-center gap-2 flex-wrap">
          <Sparkles className="h-5 w-5" />
          <span className="font-semibold">✨ Demo – PetPort LiveLink</span>
          <a href="/#pricing">
            <Button 
              variant="outline" 
              size="sm"
              className="ml-4 bg-white text-brand-primary hover:bg-brand-cream border-white"
            >
              Get Started Today
            </Button>
          </a>
        </div>
      </div>

      <main className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Care Instructions Section */}
        <CareInstructionsSection 
          petData={pet}
        />

        {/* Footer CTA */}
        <div className="bg-gradient-to-r from-brand-primary to-brand-secondary rounded-lg p-8 text-center text-white mt-8 mb-6">
          <h2 className="text-2xl font-bold mb-3">Ready to Create Care Instructions for Your Pet?</h2>
          <p className="mb-4 text-white/90">Join thousands of pet owners keeping caregivers informed</p>
          <a href="/#pricing">
            <Button 
              size="lg"
              className="bg-white text-brand-primary hover:bg-brand-cream"
            >
              Get Started Today
            </Button>
          </a>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-gray-500 text-sm pb-8">
          <div className="border-t border-sage-200 mb-6 max-w-md mx-auto" />
          <p>This is a live demo of {pet.name}'s real PetPort care instructions.</p>
          <p className="mt-2">
            Generated by{" "}
            <a 
              href={window.location.origin}
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline font-medium"
            >
              PetPort.app
            </a>
            {" "}— Be ready for travel, sitters, lost pet, and emergencies. Try it free.
          </p>
        </div>
      </main>
    </div>
  );
}
