import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Download, Loader2, Eye } from "lucide-react";
import { toast } from "sonner";
import { generateFreeLostPetFlyer } from "@/services/freeFlyerService";

export const FreeLostPetFlyerGenerator = () => {
  const [petName, setPetName] = useState("");
  const [species, setSpecies] = useState("");
  const [contactPhone, setContactPhone] = useState("");
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [flyerPreview, setFlyerPreview] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 10 * 1024 * 1024) {
        toast.error("Image must be smaller than 10MB");
        return;
      }
      setPhotoFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setPhotoPreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const validateForm = () => {
    if (!petName.trim()) {
      toast.error("Please enter your pet's name");
      return false;
    }
    if (!species) {
      toast.error("Please select a species");
      return false;
    }
    if (!contactPhone.trim()) {
      toast.error("Please enter your contact phone");
      return false;
    }
    if (!photoFile) {
      toast.error("Please upload a photo of your pet");
      return false;
    }
    return true;
  };

  const generatePreview = async () => {
    if (!validateForm()) return;

    setIsGenerating(true);

    try {
      // Create a canvas to preview the flyer
      const canvas = document.createElement('canvas');
      canvas.width = 794; // A4 width in pixels at 96 DPI
      canvas.height = 1123; // A4 height in pixels at 96 DPI
      const ctx = canvas.getContext('2d');
      
      if (!ctx) throw new Error('Could not get canvas context');

      // White background
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Red header
      ctx.fillStyle = '#dc2626';
      ctx.fillRect(0, 0, canvas.width, 132);

      // Title
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 72px Arial';
      ctx.textAlign = 'center';
      ctx.fillText('MISSING PET', canvas.width / 2, 90);

      // Load and draw pet photo
      const img = new Image();
      img.src = photoPreview!;
      await new Promise((resolve) => { img.onload = resolve; });

      const maxWidth = canvas.width - 120;
      const maxHeight = 450;
      let imgWidth = maxWidth;
      let imgHeight = (img.height * maxWidth) / img.width;
      
      if (imgHeight > maxHeight) {
        imgHeight = maxHeight;
        imgWidth = (img.width * maxHeight) / img.height;
      }

      const xPos = (canvas.width - imgWidth) / 2;
      ctx.drawImage(img, xPos, 170, imgWidth, imgHeight);

      // Pet name
      let yPos = 170 + imgHeight + 60;
      ctx.fillStyle = '#000000';
      ctx.font = 'bold 64px Arial';
      ctx.fillText(petName.toUpperCase(), canvas.width / 2, yPos);

      // Species
      yPos += 50;
      ctx.font = '42px Arial';
      ctx.fillText(species, canvas.width / 2, yPos);

      // Contact box
      yPos += 80;
      ctx.strokeStyle = '#dc2626';
      ctx.lineWidth = 4;
      ctx.strokeRect(60, yPos - 20, canvas.width - 120, 95);

      yPos += 20;
      ctx.font = 'bold 32px Arial';
      ctx.fillText('IF FOUND, PLEASE CONTACT:', canvas.width / 2, yPos);

      yPos += 45;
      ctx.fillStyle = '#dc2626';
      ctx.font = 'bold 50px Arial';
      ctx.fillText(contactPhone, canvas.width / 2, yPos);

      // Footer
      const footerY = canvas.height - 60;
      ctx.fillStyle = '#787878';
      ctx.font = '24px Arial';
      ctx.fillText('Generated by PetPort.app', canvas.width / 2, footerY);
      
      ctx.font = '20px Arial';
      ctx.fillText('Get QR codes, real-time updates, and sighting alerts at petport.app', canvas.width / 2, footerY + 30);

      // Convert canvas to data URL
      const previewUrl = canvas.toDataURL('image/png');
      setFlyerPreview(previewUrl);
      setShowPreview(true);

      toast.success("Preview generated! Scroll down to see it.");
    } catch (error) {
      console.error("Error generating preview:", error);
      toast.error("Failed to generate preview. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    if (!validateForm()) return;

    setIsGenerating(true);

    try {
      await generateFreeLostPetFlyer({
        petName: petName.trim(),
        species,
        contactPhone: contactPhone.trim(),
        photoFile: photoFile!
      });

      toast.success("Lost pet flyer downloaded successfully!");
    } catch (error) {
      console.error("Error generating flyer:", error);
      toast.error("Failed to generate flyer. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Card className="border-2 border-destructive/20 shadow-lg">
      <CardContent className="p-6 md:p-8">
        <div className="space-y-6">
          <div className="grid md:grid-cols-2 gap-6">
            {/* Left Column - Form Fields */}
            <div className="space-y-4">
              <div>
                <Label htmlFor="pet-name">Pet Name *</Label>
                <Input
                  id="pet-name"
                  placeholder="e.g., Max"
                  value={petName}
                  onChange={(e) => setPetName(e.target.value)}
                  maxLength={50}
                />
              </div>

              <div>
                <Label htmlFor="species">Species *</Label>
                <Select value={species} onValueChange={setSpecies}>
                  <SelectTrigger id="species">
                    <SelectValue placeholder="Select species" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Dog">Dog</SelectItem>
                    <SelectItem value="Cat">Cat</SelectItem>
                    <SelectItem value="Bird">Bird</SelectItem>
                    <SelectItem value="Rabbit">Rabbit</SelectItem>
                    <SelectItem value="Other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="contact-phone">Contact Phone *</Label>
                <Input
                  id="contact-phone"
                  type="tel"
                  placeholder="(555) 123-4567"
                  value={contactPhone}
                  onChange={(e) => setContactPhone(e.target.value)}
                  maxLength={20}
                />
              </div>
            </div>

            {/* Right Column - Photo Upload */}
            <div className="space-y-4">
              <Label htmlFor="pet-photo">Pet Photo *</Label>
              <div className="border-2 border-dashed border-border rounded-lg p-4 text-center">
                {photoPreview ? (
                  <div className="space-y-2">
                    <img 
                      src={photoPreview} 
                      alt="Preview" 
                      className="w-full h-48 object-cover rounded-lg"
                    />
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        setPhotoFile(null);
                        setPhotoPreview(null);
                      }}
                    >
                      Remove Photo
                    </Button>
                  </div>
                ) : (
                  <label htmlFor="pet-photo" className="cursor-pointer block py-8">
                    <div className="text-muted-foreground">
                      <p className="font-medium">Click to upload photo</p>
                      <p className="text-sm mt-1">Max 10MB - JPG, PNG</p>
                    </div>
                    <Input
                      id="pet-photo"
                      type="file"
                      accept="image/jpeg,image/png,image/jpg"
                      onChange={handlePhotoChange}
                      className="hidden"
                    />
                  </label>
                )}
              </div>
            </div>
          </div>

          <div className="pt-4 space-y-3">
            <div className="grid md:grid-cols-2 gap-3">
              <Button
                onClick={generatePreview}
                disabled={isGenerating}
                size="lg"
                variant="outline"
                className="w-full"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Eye className="mr-2 h-5 w-5" />
                    Preview Flyer
                  </>
                )}
              </Button>
              
              <Button
                onClick={handleDownload}
                disabled={isGenerating}
                size="lg"
                className="w-full bg-destructive hover:bg-destructive/90 text-white"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Download className="mr-2 h-5 w-5" />
                    Download PDF
                  </>
                )}
              </Button>
            </div>
          </div>

          <div className="text-center text-sm text-muted-foreground pt-2">
            <p>No signup required • Instant download • Free forever</p>
          </div>

          {showPreview && flyerPreview && (
            <div className="mt-8 pt-8 border-t">
              <h3 className="text-xl font-semibold mb-4 text-center">Flyer Preview</h3>
              <div className="bg-muted/30 p-4 rounded-lg">
                <img 
                  src={flyerPreview} 
                  alt="Flyer Preview" 
                  className="w-full max-w-2xl mx-auto rounded-lg shadow-xl border-2 border-border"
                />
                <p className="text-sm text-muted-foreground text-center mt-4">
                  This is how your flyer will look. Click "Download PDF" above to save it.
                </p>
              </div>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};
